spring.application.name=rag
langchain4j.google.ai.gemini.api-key=SUA_API_KEY
langchain4j.google.ai.gemini.model-name=gemini-2.5-flash

spring.ai.vectorstore.pgvector.initialize-schema=true

# Suppress WARN logs from FileSystemFontProvider
logging.level.org.apache.pdfbox.pdmodel.font.FileSystemFontProvider=ERROR

spring.docker.compose.lifecycle-management=start_only